spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:sukhwa
        username: sukhwa
        password: 
        driver-class-name: org.h2.Driver
